### PR TITLE
Allow rich_rules to be specified as a dictionary

### PR DESCRIPTION
**Pull request by Sxderp**
When specifying rich rules as a dictionary ipsets and services can be
specified as lists. They will be expanded out by the jinja template into
individual rich rules for the parent zone.

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [x] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Similar to #39

### Describe the changes you're proposing

No functionality is broken. If rich rules are specified as a list then all
the processing is ignore and the list is directly passed into the template,
as before.

This PR is similar to #39 . But it includes added functionality. The ability
for services and ipsets to be expanded, which allows for zone-like
configuration.

The goal of this PR was to allow extending rich rules between different
pillar files. Since lists are not merged (by default) between pillar files,
you are required to list all rich rules in a single file. By using a dictionary
we can properly extend the rules.

Use of the special keys "ipsets" and "services" was added for my
environment in particular, allowing for grouping of services and ipsets
similar to zones. I figured it might get enough traction to warrant
inclusion upstream.

### Pillar / config required to test the proposed changes

```yaml
firewalld:
  enabled: true
  ipset:
    manage: true
    pkg: ipset
  ipsets:
    fail2ban-ssh:
      short: fail2ban-ssh
      description: fail2ban-ssh
      type: 'hash:ip'
      entries:
        - 10.0.0.1
    other-ipset:
      short: other-ipset
      description: other-ipset
      type: 'hash:ip'
      entries:
        - 10.0.0.2
  zones:
    rich_public:
      short: rich_public
      description: "Example"
      rich_rules:
        ssh-rr:
          accept: true
          ipsets:
            - fail2ban-ssh
            - other-ipset
          services:
            - ssh
            - http
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by Sxderp** [comment]
Rebased and pushed. Added `feat:` to commit and chopped to characters off a comment for lint.

**Comment by myii** [comment]
@Sxderp Thanks for the contribution.  To make this easier to review, I'd like to add some tests for this.  To begin with, for the pillar/config you've shared, can you show how this would be rendered in the XML file?  It would also be helpful if you give an example of the existing list method, showing the pillar and the rendered XML.  We can then take those and add them to the test pillar, as well as use InSpec to confirm the rendered XML contains the changes we're expecting.  Are you OK with doing this?

**Comment by Sxderp** [comment]
I'll provide the XML files. Give me a day or two.

**Comment by myii** [comment]
@Sxderp Thanks, please take your time.  I don't need the entire files, just the specific sections related to `rich_rules`, showing what to expect if using a list versus using a dict.

**Comment by Sxderp** [comment]
With the following pillar (slightly expanded from above, to include the list) I get the below xmls:

```yaml
firewalld:
  enabled: true
  ipset:
    manage: true
    pkg: ipset

  ipsets:
    fail2ban-ssh:
      short: fail2ban-ssh
      description: fail2ban-ssh
      type: 'hash:ip'
      entries:
        - 10.0.0.1
    other-ipset:
      short: other-ipset
      description: other-ipset
      type: 'hash:ip'
      entries:
        - 10.0.0.2

  zones:
    rich_public:
      short: rich_public
      description: "Example"
      rich_rules:
        ssh-rr:
          accept: true
          ipsets:
            - fail2ban-ssh
            - other-ipset
          services:
            - ssh
            - http

    rich_list_public:
      short: rich_list_public
      description: "Example"
      rich_rules:
        - accept: true
          ipset:
            name: fail2ban-ssh
          service: https
        - accept: true
          ipset:
            name: other-ipset
          service: https
```

rich_public.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  This file is managed/generated by salt.
  Do not edit this file manually, it will be overwritten!
  Modify the salt pillar for firewalld instead
-->
<zone>
  <short>rich_public</short>
  <description>Example</description>

  <rule>
    <source ipset="fail2ban-ssh" />
    <service name="ssh" />
    <accept/>    
  </rule>

  <rule>
    <source ipset="fail2ban-ssh" />
    <service name="http" />
    <accept/>    
  </rule>

  <rule>
    <source ipset="other-ipset" />
    <service name="ssh" />
    <accept/>    
  </rule>

  <rule>
    <source ipset="other-ipset" />
    <service name="http" />
    <accept/>    
  </rule>

</zone>
```

rich_list_public.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  This file is managed/generated by salt.
  Do not edit this file manually, it will be overwritten!
  Modify the salt pillar for firewalld instead
-->
<zone>
  <short>rich_list_public</short>
  <description>Example</description>

  <rule>
    <source ipset="fail2ban-ssh" />
    <service name="https" />
    <accept/>    
  </rule>

  <rule>
    <source ipset="other-ipset" />
    <service name="https" />
    <accept/>    
  </rule>

</zone>
```

**Comment by myii** [comment]
@Sxderp Great, can you also do the same for the original list method?  That will make it much easier to write the tests.

**Comment by Sxderp** [comment]
Git makes that simple enough.

Seems my patch adds some spacing to the resulting zone file. If necessary I think that can be fixed.

```yaml
firewalld:
  enabled: true
  ipset:
    manage: true
    pkg: ipset

  ipsets:
    fail2ban-ssh:
      short: fail2ban-ssh
      description: fail2ban-ssh
      type: 'hash:ip'
      entries:
        - 10.0.0.1
    other-ipset:
      short: other-ipset
      description: other-ipset
      type: 'hash:ip'
      entries:
        - 10.0.0.2

  zones:
    rich_list_public_old:
      short: rich_list_public_old
      description: "Example"
      rich_rules:
        - accept: true
          ipset:
            name: fail2ban-ssh
          service: https
        - accept: true
          ipset:
            name: other-ipset
          service: https
```

rich_list_public_old.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  This file is managed/generated by salt.
  Do not edit this file manually, it will be overwritten!
  Modify the salt pillar for firewalld instead
-->
<zone>
  <short>rich_list_public_old</short>
  <description>Example</description>
  <rule>
    <source ipset="fail2ban-ssh" />
    <service name="https" />
    <accept/>    
  </rule>
  <rule>
    <source ipset="other-ipset" />
    <service name="https" />
    <accept/>    
  </rule>
</zone>
```

**Comment by myii** [comment]
@Sxderp Thanks, I'll look into these soon to figure out some tests to add here.

**Comment by myii** [comment]
@Sxderp Got the tests written up and tested locally.  Also made the whitespacing fix.  Let me just run it in Travis now:

* https://travis-ci.org/github/myii/firewalld-formula/builds/669795396

If that works out, I'll push it on top of your commit and we can discuss it further.

**Comment by myii** [comment]
@Sxderp So it worked, the `arch-base-latest` failure was because of some service tests that I also added.  The main parts I'd like your feedback on:

* https://github.com/myii/firewalld-formula/commit/eeb79d31a126b17f02dc6f2f06a969a1d6cd80bc
  - The two files have been effectively copied across verbatim, without the extra line breaks.
  - We don't want false positives with existing zone files being "changed" due to these.
* https://github.com/myii/firewalld-formula/commit/865fb21e61ed6164b670ef029093f879a82066fa
  - I'd prefer the `macro` definition at the top of the file.
  - There were two fixes for the extra line breaks covered at the top and bottom of [this block](https://github.com/myii/firewalld-formula/commit/865fb21e61ed6164b670ef029093f879a82066fa#diff-1aa105146db90d6c723853d3fdb305efR183-L188).

**Comment by myii** [comment]
@Sxderp Actually, I've just gone ahead and added the two good commits here, so we can link to it in the review tools available in this PR itself.  Please feel free to comment, if there's an issue, we can always remove/adjust the commits.

**Comment by myii** [comment]
@Sxderp OK, so the tests have helped uncover an issue with trailing whitespaces:

* https://travis-ci.com/github/saltstack-formulas/firewalld-formula/jobs/311605982#L330-L341
  - (The errors above that will be fixed with a small adjustment to that I'll make to `.rubocop.yml`).

So this has helped uncover that there are a number of lines with trailing whitespaces in the `zone.xml` template.  That _does_ need to be fixed in my opinion, so I'll adjust that as well and update the tests.

**Comment by myii** [comment]
OK, that all worked: https://travis-ci.org/github/myii/firewalld-formula/builds/669810643.  Force pushing the changes back here.

**Comment by Sxderp** [comment]
>    myii@eeb79d3
>        The two files have been effectively copied across verbatim, without the extra line breaks.
>        We don't want false positives with existing zone files being "changed" due to these.

From my limited knowledge of the testing framework looks good. But I'll defer to you.

>    myii@865fb21
>        I'd prefer the macro definition at the top of the file.
>        There were two fixes for the extra line breaks covered at the top and bottom of this block.

Sure. The only reason the macro was near the bottom was it took fewer changes for me to implement what I wanted. Moving to the top is fine.

> OK, so the tests have helped uncover an issue with trailing whitespaces:

Interesting. I have my VIM highlight trailing spaces in bright red. Surprised I didn't see anything. Although, if they were there previously doesn't this cause the "False-Positive" issue; same as adding line breaks?

**Comment by myii** [comment]
> Interesting. I have my VIM highlight trailing spaces in bright red. Surprised I didn't see anything.

I had the same issue with Vim!  I was surprised so I went back to the current `master` branch but it was there alright.  Perhaps Vim ignores trailing whitespace in XML files by default?  It does get highlighted by `vim-airline`, to be fair.

> Although, if they were there previously doesn't this cause the "False-Positive" issue; same as adding line breaks?

The difference here is that the trailing whitespace should never have been there in the first place (an error that should be fixed).  If the original template had resulted in blank lines, then I would have wanted to maintain that instead with the tests, to avoid false-positives.

---

So are you OK with this being merged with the additions, @Sxderp?

**Comment by Sxderp** [comment]
> So are you OK with this being merged with the additions

Yes. Good to go.

**Comment by myii** [comment]
Thanks for providing this new feature, @Sxderp -- merged.

**Pull request merged**
